site_name: Mkdocs Template
site_description: A website template for using mkdocs
site_author: Qiusheng Wu
site_url: https://ZoloKiala.github.io/mkdocs-demo

repo_url: https://github.com/ZoloKiala/mkdocs-demo

copyright: "Copyright &copy; 2022 - 2025 Qiusheng Wu"

theme:
  palette:
    - scheme: default
      #   primary: blue
      #   accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - search.highlight
  custom_dir: "docs/overrides"
  font:
    text: Google Sans
    code: Regular

plugins:
  - search
  - mkdocstrings
  - git-revision-date
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True
      execute: True
      allow_errors: false
      ignore: ["name.ipynb"]
      execute_ignore: ["path/*.ipynb"]

markdown_extensions:
  - attr_list
  - toc:
      permalink: true

# extra:
#   analytics:
#     provider: google
#     property: G-XXX

nav:
  - Home: index.md
  - Notebook:
      - template.ipynb
  - Datasets:
      - Datasets/Name of project/intro.ipynb
      - Datasets/Name of project/basemaps.ipynb
  - Google earth engine:
      - Google earth engine/Name of project/colorbar.ipynb
      - Google earth engine/Name of project/heatmap.ipynb
  - Pre-trained models:
      - Pre-trained models/Name of project/colorbar.ipynb
      - Pre-trained models/Name of project/Datasets/chapter_03/heatmap.ipynb
  - Python:
      - Python/Name of project/colorbar.ipynb
      - Python/Name of project/heatmap.ipynb
  - YouTube Channel: https://www.youtube.com/@iwmi
  - Report Issues: https://github.com/iwmihq/iwmi-water-data-science/issues
